version: 2
updates:
- package-ecosystem: cargo
  directories:
  - /
  - /.github/coverage-runtime
  - /tests/browser
  schedule:
    interval: daily
  open-pull-requests-limit: 1
  groups:
    cargo:
      patterns:
      - '*'
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  groups:
    actions:
      patterns:
      - '*'
- package-ecosystem: npm
  directory: /clients/ts
  schedule:
    interval: weekly
  open-pull-requests-limit: 1
  groups:
    npm:
      patterns:
      - '*'
